# Token helper cho IntelliJ HTTP Client
#
# Chạy các request này sau `make keycloak-up && make keycloak-setup`.
# Script cuối mỗi request set global variable trong phiên IDE:
# - tenant1_token
# - tenant2_token
# - admin_token
#
# Nếu muốn lưu qua nhiều phiên IntelliJ, copy token vào file local:
# `lab-code/http-client.env.json` hoặc `http-client.private.env.json`.
# Không commit token thật.

@keycloak_base_url = http://localhost:18080
@keycloak_realm = viettel-lab
@keycloak_client_id = tenant-demo-api-client
@demo_password = password

### 0. Keycloak OIDC discovery
GET {{keycloak_base_url}}/realms/{{keycloak_realm}}/.well-known/openid-configuration

### 1. Token tenant1 ACCOUNTANT
POST {{keycloak_base_url}}/realms/{{keycloak_realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{keycloak_client_id}}&username=tenant1-user&password={{demo_password}}

> {%
    client.test("tenant1 token ok", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("tenant1_token", response.body.access_token);
    client.log("Updated global variable: tenant1_token");
%}

### 2. Token tenant2 VIEWER
POST {{keycloak_base_url}}/realms/{{keycloak_realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{keycloak_client_id}}&username=tenant2-user&password={{demo_password}}

> {%
    client.test("tenant2 token ok", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("tenant2_token", response.body.access_token);
    client.log("Updated global variable: tenant2_token");
%}

### 3. Token platform admin ADMIN
POST {{keycloak_base_url}}/realms/{{keycloak_realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{keycloak_client_id}}&username=platform-admin&password={{demo_password}}

> {%
    client.test("admin token ok", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("admin_token", response.body.access_token);
    client.log("Updated global variable: admin_token");
%}
